In [1]:
import pandas as pd
import numpy as np

In [2]:
# Importamos el archivo json que contiene los datos de los usuarios de streaming
df = pd.read_json('../data/raw/streaming_users_dirty.json')

In [3]:
# Inspeccionamos el dataframe
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 8160 entries, 0 to 8159
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   8160 non-null   int64
 1   age                       8160 non-null   int64
 2   subscription_plan         8160 non-null   str
 3   monthly_watch_time_mins   7967 non-null   float64
 4   country                   8160 non-null   str
 5   favorite_genre            7920 non-null   str
 6   last_login_date           7840 non-null   str
 7   customer_support_tickets  8160 non-null   int64
dtypes: float64(1), int64(3), str(4)
memory usage: 756.7 KB

(8160, 8)

El dataset cuenta con 8 columnas y 8160 filas, se detecta que fecha esta como str y no como date

In [4]:
df.describe()

,user_id,age,monthly_watch_time_mins,customer_support_tickets
count,8160.000000,8160.000000,7967.000000,8160.000000
mean,13995.433824,34.096814,1107.346153,1.800980
std,2310.810660,14.511304,5310.442604,11.334969
min,10000.000000,-5.000000,-120.000000,-1.000000
25%,11987.750000,25.000000,489.200000,0.000000
50%,13998.500000,33.000000,757.400000,1.000000
75%,15997.250000,42.000000,1045.700000,1.000000
max,17999.000000,150.000000,99999.000000,150.000000

Aqui detectamos: min y max en 'age', 'monthly_watch_time_mins' y 'customer_support_tickets' que deben ser irreales.

In [5]:
# Detectamos los valores nulos en el dataframe
df.isnull().sum()

user_id                       0
age                           0
subscription_plan             0
monthly_watch_time_mins     193
country                       0
favorite_genre              240
last_login_date             320
customer_support_tickets      0
dtype: int64

In [6]:
df.head(10)

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
0,10000,39,Estándar,805.8,Brasil,Crime,2025-03-04,99
1,10001,37,Estándar,1173.4,Colombia,Crime,2019-04-02,2
2,10002,28,Básico,401.0,Colombia,Crime,2018-04-13,0
3,10003,43,Básico,62.4,Uruguay,Thriller,2021-01-31,0
4,10004,51,Básico,477.8,Perú,Thriller,2020-09-30,1
5,10005,20,Básico,670.2,Uruguay,Drama,2020-07-03,2
6,10006,37,Básico,346.6,Perú,Thriller,2019-07-26,1
7,10007,31,Estándar,974.6,Chile,Acción,2019-02-24,1
8,10008,36,Premium,1432.2,Colombia,Romance,2025-08-03,2
9,10009,37,Estándar,1375.4,Argentina,Thriller,2024-02-12,1

In [7]:
df.duplicated().sum()

np.int64(126)

Se detectaron 126 registros duplicados absolutos que deberán ser tratados en la etapa de limpieza

In [8]:
# Detectamos los duplicados en el dataframe
df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
37,10037,33,Básico,611.0,Colombia,Documental,2019-09-29,2
8133,10037,33,Básico,611.0,Colombia,Documental,2019-09-29,2
52,10052,25,Básico,465.7,Colombia,Acción,2022-03-31,1
8089,10052,25,Básico,465.7,Colombia,Acción,2022-03-31,1
117,10117,29,Estándar,713.9,Brasil,Documental,2020-12-20,1
...,...,...,...,...,...,...,...,...
8115,17684,38,Premium,1283.2,México,Comedia,2024-09-13,0
7784,17784,38,Estándar,492.2,México,Documental,2021-10-04,1
8125,17784,38,Estándar,492.2,México,Documental,2021-10-04,1
7994,17994,24,Básico,437.0,México,Romance,2020-08-12,0
8046,17994,24,Básico,437.0,México,Romance,2020-08-12,0

In [9]:
# Filtramos todos los registros donde la columna específica se repite
df.duplicated(subset=['user_id']).sum()

np.int64(160)

In [10]:
columna_objetivo = 'user_id'

# 1. Filtramos todos los registros donde la columna específica se repite
duplicados_por_columna = df[df.duplicated(subset=[columna_objetivo], keep=False)]

# 2. Excluimos los clones absolutos (la tilde ~ invierte la condición booleana)
duplicados_parciales = duplicados_por_columna[~duplicados_por_columna.duplicated(keep=False)]

# 3. Mostramos la totalidad de las filas conflictivas ordenadas para su comparación
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(duplicados_parciales.sort_values(by=[columna_objetivo]))

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
59,10059,39,Estándar,2976.6,Brasil,DRAMA,2024-06-22,1
8090,10059,39,Estándar,824.8,Brasil,Drama,2024-06-22,1
8126,10721,32,Estándar,959.0,Colombia,Documental,2021-09-02,2
721,10721,32,Estándar,959.0,Colombia,Documental,NaN,2
797,10797,31,Básico,-1.0,México,Comedia,2023-07-01,1
8018,10797,31,Básico,410.4,México,Comedia,2023-07-01,1
8076,11092,31,Estándar,959.6,Chile,Romance,2025-01-05,2
1092,11092,31,Estándar,959.6,Chile,Romance,2025-01-05,2
1222,11222,13,Estándar,1321.8,MEX,Documental,2019-02-08,0
8157,11222,13,Estándar,1321.8,México,Documental,2019-02-08,0
8084,11292,40,Estándar,199.7,Brasil,Documental,2018-03-31,2
1292,11292,40,Estándar,199.7,Brazil,Documental,2018-03-31,2
8154,11586,17,Básico,1123.6,Brasil,Crime,2019-03-20,1
1586,11586,17,Básico,1123.6,Brasil,NaN,2019-03-20,1
8055,11746,27,Estándar,891.2,México,Acción,2019-02-26,1
1746,11746,27,Estándar,891.2,México,NaN,2019-02-26,1
1796,11796,21,Premium,1427.8,Perú,Drama,NaN,2
8146,11796,21,Premium,1427.8,Perú,Drama,2022-04-24,2
8051,12634,22,Básico,730.3,Colombia,Drama,2019-03-16,0
2634,12634,-5,Básico,730.3,Colombia,Drama,2019-03-16,0
3081,13081,46,Estándar,260.1,México,Crime,NaN,2
8082,13081,46,Estándar,260.1,México,Crime,2024-03-13,2
8043,13293,31,Premium,1018.5,Argentina,Crime,2025-07-19,0
3293,13293,31,Premium,1018.5,Argentina,Crimen,2025/07/19,0
3491,13491,0,Básico,790.3,Brasil,Acción,2024-12-12,0
8037,13491,41,Básico,790.3,Brasil,Acción,2024-12-12,0
8019,13737,23,Premium,1178.8,Argentina,Thriller,2022-04-22,2
3737,13737,23,Premium,1178.8,Argentina,Thriller,NaN,2
3802,13802,33,Básico,482.4,Perú,NaN,2022-08-29,1
8147,13802,33,Básico,482.4,Perú,Comedia,2022-08-29,1
4095,14095,13,Premium,NaN,Chile,Crime,2020-05-29,1
8123,14095,13,Premium,1574.8,Chile,Crime,2020-05-29,1
8138,14343,46,Premium,832.5,Perú,Comedia,2018-07-23,0
4343,14343,46,Premium,832.5,Perú,Comedia,2018-07-23,0
8023,14841,22,Estándar,886.3,Perú,Acción,2019-09-20,0
4841,14841,22,Estándar,886.3,Perú,Acción,20-09-2019,0
8058,14858,62,Estándar,503.7,Uruguay,Drama,2022-09-12,3
4858,14858,62,Estándar,503.7,uruguay,Drama,2022-09-12,3
5001,15001,25,Básico,246.3,Argentina,Comedia,17-02-2018,0
8117,15001,25,Básico,246.3,Argentina,Comedia,2018-02-17,0
5013,15013,13,Premium,1407.1,Brazil,Crime,2021-02-13,2
8124,15013,13,Premium,1407.1,Brasil,Crime,2021-02-13,2
5017,15017,33,STANDARD,386.8,Colombia,Thriller,2024-03-04,1
8081,15017,33,Estándar,386.8,Colombia,Thriller,2024-03-04,1
8004,15065,33,Premium,1070.6,Chile,Drama,2023-01-28,0
5065,15065,33,Premium,3475.8,Chile,Drama,2023-01-28,0
8012,15182,19,Premium,1612.3,Perú,Thriller,2021-03-17,2
5182,15182,19,Premium,NaN,Perú,Thriller,2021-03-17,2
5314,15314,30,Estándar,1106.0,Argentina,Documental,07-02-2025,0
8008,15314,30,Estándar,1106.0,Argentina,Documental,2025-07-02,0
8158,15613,38,Estándar,835.7,Brasil,Drama,2022-02-05,0
5613,15613,38,Estándar,835.7,Brazil,Drama,2022-02-05,0
8067,15704,48,Estándar,1313.8,Uruguay,Romance,2023-02-01,1
5704,15704,48,Estándar,99999.0,Uruguay,Romance,2023-02-01,1
6045,16045,44,Estándar,1294.4,México,accion,2023-04-15,1
8041,16045,44,Estándar,1294.4,México,Acción,2023-04-15,1
8078,16480,48,Básico,810.2,México,Thriller,2024-03-08,1
6480,16480,48,Básico,810.2,Mexico,Thriller,2024-03-08,1
6770,16770,52,Estándar,1039.2,Argentina,Acción,NaN,2
8128,16770,52,Estándar,1039.2,Argentina,Acción,2018-04-04,2
8022,16843,22,Básico,501.4,Argentina,Acción,2025-09-03,2
6843,16843,22,Básico,3949.0,Argentina,Acción,2025-09-03,2
7410,17410,25,Premium,1614.9,Uruguay,Romance,2021-12-27,-1
8014,17410,25,Premium,1614.9,Uruguay,Romance,2021-12-27,1
7520,17520,20,Estándar,826.5,Brasil,Acción,09-09-2018,1
8003,17520,20,Estándar,826.5,Brasil,Acción,2018-09-09,1
7902,17902,30,Básico,505.7,Brasil,THRILLER,2025-06-15,0
8053,17902,30,Básico,505.7,Brasil,Thriller,2025-06-15,0

In [11]:
# Detectamos los valores únicos de la columna 'country'
df['country'].unique()

<ArrowStringArray>
[    'Brasil',   'Colombia',    'Uruguay',       'Perú',      'Chile',
  'Argentina',     'México',     'Brazil',     'brasil',     'méxico',
      'chile',    'uruguay',        'MEX',        'ARG',   'colombia',
        'COL',     'Mexico',        'URY',     'Chile ',       'Peru',
       'perú',  'argentina',        'PER', 'Argentina ',        'BRA',
        'CHL']
Length: 26, dtype: str

In [12]:
# Detectamos los valores únicos de la columna 'favorite_genre'
df['favorite_genre'].unique()

<ArrowStringArray>
[      'Crime',    'Thriller',       'Drama',      'Acción',     'Romance',
     'Comedia',  'Documental',      'ACCIÓN',           nan,       'CRIME',
    'Comedia ',      'comedy',       'DRAMA',    'THRILLER', 'Documentary',
   'Thriller ',      'accion',      'Action',     'COMEDIA',     'ROMANCE',
     'thriler',         'DOC',     'romance',      'Crimen',      'Drama ',
       'drama',    'Romance ',  'documental',       'crime']
Length: 29, dtype: str

In [13]:
df['subscription_plan'].unique()

<ArrowStringArray>
[ 'Estándar',    'Básico',   'Premium',       'Std',  'estandar',    'basico',
    'básico',  'Premium ',   'premium',   'Premiun',    'BASICO',  'STANDARD',
     'Basic', 'Estándar ',   'PREMIUM']
Length: 15, dtype: str

En el analisis detecte que hay duplicados exactos en todas las filas (126) pero el ID se repite 160 veces, por lo que hay 34 registros que son coincidencias parciales. Ademas vemos las variantes de cada fila tipo string para noralizar.